version: '3.8'
services:
  db:
    container_name: db
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  bot:
    build: .
    links:
      - db
    depends_on:
      - db
volumes:
  db:
    driver: local
