"""empty message

Revision ID: 4a5c047ebd86
Revises: 0e14368e1390
Create Date: 2023-06-05 23:58:17.163214

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4a5c047ebd86'
down_revision = '0e14368e1390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity')
    # ### end Alembic commands ###
